### PR TITLE
Adding a Json container encapsulating the object value

### PR DESCRIPTION
**Pull request by bmontuelle**
Hello, 

I found your library useful for handling json serialization of case classes using traits, thanks for sharing it.
For backward-compatibility reasons I had to adjust the serialisation format and encapsulate the object value in a distinct js object.

You may not be interested in this at all, just wanted to let you know what we're doing here

### CODE REVIEW

**Comment by leonardehrenfried** [comment]
Hi, this looks interesting but is backwards-incompatible with already existing JSON.

I'd glady merge this in, but the user would have to explicitly specify the which type of serialisation they want with the default being the old way.

Something like 
```scala
traitFormat[Animal](serializationStrategy = SubProperty)
traitFormat[Animal](serializationStrategy = MergedObject)
traitFormat[Animal] // means the same as above
```

This way both strategies can coexist with each other.

Are you interested in implementing this and writing specs for it?

**Comment by bmontuelle** [comment]
Yes, that could be a fine solution for me, I'll work on this and update the PR

**Comment by bmontuelle** [comment]
I tried not to move everything and keep the API backward compatible so I added a second spec for the SubProperty serialization strategy and keep all the previous test cases unchanged.

Please let me know if this is more suitable to you, on my client project I'll just add a wrapper to provide the serialization strategy and the property names and it should be fine

**Comment by leonardehrenfried** [comment]
This is an excellent change. I'm going to merge this in, make a few minor modifications and create a release on Maven Central.

Is there any chance that you could add a little bit of documentation to the README?

**Comment by leonardehrenfried** [comment]
Version 1.4.0 has been released. It should show up in Maven Central in a few minutes.

**Comment by bmontuelle** [comment]
Thanks, I'll update the README later on today

**Pull request merged**
